Repository wecode-bootcamp-korea/30-1st-ChickIN-frontend, pull requests merged in 2022-03, with the labels that each got.

#5 [30기 강성훈] Modify: initial setting changes for the naming convention / Nav, Footer component : showing them up everywhere
  src/Router.js
  src/index.js
  src/pages/Goods_list/GoodsList.js
  src/pages/Goods_list/Goods_card/Goods_card.js
  src/pages/Goods_list/Goods_list.js
  src/pages/Goods_view/GoodsView.js
  src/pages/Goods_view/Goods_view.js
  src/pages/Main/Main.js
Labels: Status: 리뷰 요청

#7 [30기 이상민] Footer 리뷰반영
  package-lock.json
  package.json
  src/Router.js
  src/components/Footer/Footer.js
  src/components/Footer/Footer.scss
  src/pages/Goods_view/GoodsView.scss
  src/pages/Main/Main.js
  src/pages/Main/Main.scss
Labels: Status: 수정 요청, Status: 리뷰 요청

#10 [30기 이상민] [Footer] scss 수정 및 리뷰반영
  src/components/Footer/Footer.js
  src/components/Footer/Footer.scss
Labels: Status: 리뷰 요청

#8 [30기 강성훈] Add : GoodsList and GoodsCard component 구현중
  package-lock.json
  package.json
  public/data/mock.json
  public/data/mock2.json
  src/Router.js
  src/components/Nav/Nav.scss
  src/pages/Goods_list/GoodsList.js
  src/pages/Goods_list/GoodsList.scss
  src/pages/Goods_list/Goods_card/GoodsCard.js
  src/pages/Goods_list/Goods_card/GoodsCard.scss
  src/pages/Goods_list/Goods_card/Goods_card.js
  src/pages/Goods_list/SubCategories/SubCategories.js
  src/pages/Goods_list/SubCategories/SubCategories.scss
  src/styles/reset.scss
Labels: Status: 리뷰 요청

#12 [30기 강성훈] added login scss file ( 누락 문제 해결!)
  src/components/Login/Login.scss
Labels: Status: 리뷰 요청

#3 [30기 강성훈] Add: Navbar Component 이중 메뉴 구현중
  package-lock.json
  src/Router.js
  src/components/Nav/Nav.js
  src/components/Nav/Nav.scss
  src/pages/GoodsList/GoodsList.js
  src/pages/GoodsList/GoodsList.scss
  src/pages/GoodsList/Goods_card/GoodsCard.js
  src/pages/GoodsList/Goods_card/GoodsCard.scss
  src/pages/GoodsList/SubCategories/SubCategories.js
  src/pages/GoodsList/SubCategories/SubCategories.scss
  src/pages/GoodsView/GoodsView.js
  src/pages/GoodsView/GoodsView.scss
  src/pages/GoodsView/Main_options_box/MainOptionsBox.js
  src/pages/GoodsView/Main_options_box/MainOptionsBox.scss
  src/pages/GoodsView/Sub_options_box/SubOptionsBox.js
  src/pages/GoodsView/Sub_options_box/SubOptionsBox.scss
  src/pages/GoodsView/mock.json
  src/pages/Goods_view/GoodsView.scss
  src/pages/Main/Main.js
Labels: Status: Conflict 해결 요청

#15 [30기 강성훈] Add: 누락된 navbar 로고 추가
  public/images/logo.png
  src/components/Nav/Nav.js
Labels: Status: 리뷰 요청
